# Generated by Django 5.2.5 on 2025-08-31 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_level_alter_doctor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField()),
                ('time_in_hours', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_exam', to='users.doctor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_level', to='users.level')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('choice_a', models.CharField(max_length=225)),
                ('choice_b', models.CharField(max_length=225)),
                ('choice_c', models.CharField(max_length=225)),
                ('choice_d', models.CharField(max_length=225)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_doc', to='users.doctor')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_exam', to='exam.exam')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='qs_imgs', to='exam.questionimages')),
            ],
        ),
    ]
