# Generated by Django 5.2.5 on 2025-08-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='qs_imgs', to='exam.questionimages'),
        ),
    ]
