# Generated by Django 5.2.5 on 2025-09-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='solve_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=15),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_solve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE')], default='PENDING', max_length=10),
        ),
    ]
