# Generated by Django 5.2.5 on 2025-09-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_solve_status_exam_start_solve_exam_status'),
        ('users', '0004_level_alter_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDegrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_degree_exams', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_degrees', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
