# Generated by Django 5.2.5 on 2025-09-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_studentdegrees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdegrees',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
    ]
